# Generated by Django 4.0.6 on 2022-07-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('comapany_name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=255)),
                ('zip', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('web', models.CharField(max_length=255)),
            ],
        ),
    ]
