# Generated by Django 4.0.6 on 2022-07-16 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='comapany_name',
            new_name='company_name',
        ),
    ]
